### ISSUE TITLE
move 'x' position to the right of tab

### ISSUE THREAD

**Issue by N-Halv** [sequelpro/sequelpro#2539]
This issue is regarding the 'x' button for the tabs.
I propose the the close tab 'x' should be at the right side of the tab. Sometimes when performing a slowish double click on the '+' button to open a new tab the first click opens a new tab and the second click closes the tab because the 'x' is where the '+' just was.

**Comment by dmoagx** [comment]
Tabs are actually one of the features causing constant headaches in Sequel Pro.
Since Apple wants to support tabs natively in 10.12 we are strongly considering switching to that instead, in which case our tab support would only remain for backwards compatibility with older OS X versions which in turn means bugfixes only.

**Comment by abhibeckert** [comment]
This problem has been fixed (while still keeping the X on the left, as per the design standard for Mac apps) in the next release.

You can test it here: https://sequelpro.com/Sequel_Pro_r50a0f18540.dmg

**Comment by javierenciso** [comment]
what happened with this? I still have this issue ending 2018 (Sequel Pro 1.1.2 build 4541 (602e11a) with Mojave
