### ISSUE TITLE
Application Icon is not good

### ISSUE THREAD

**Issue by mkwsra** [sequelpro/sequelpro#2623]
Hi All,

Thanks for this amazing App!

The application icon seems to have a transparent outer glow as background with sharp edges (not faded out properly or it's a mistake!).

Figure:
<img width="217" alt="screen shot 2016-11-24 at 8 30 43 pm" src="https://cloud.githubusercontent.com/assets/1743919/20607344/1552f5d2-b280-11e6-90a1-78be1f1cfc58.png">

To be honest, it's a minor issue I know, but it seems very bad when you use

**Comment by luisinder** [comment]
Same problem

<img width="332" alt="captura de pantalla 2016-12-15 a las 9 07 29" src="https://cloud.githubusercontent.com/assets/6973356/21218018/2b2bdbaa-c2af-11e6-92e8-6f1d9965274c.png">

**Comment by Envo** [comment]
Same here.

**Comment by mkwsra** [comment]
I began to get used to it like this when I'm switching between the apps 😄
When it will be changed I'll feel the difference again 😆

**Comment by abhibeckert** [comment]
Confirmed, document icons have the same problem.

**Comment by BeardTech** [comment]
Hello guys replace the icon to this one with cmd+i : http://i.imgur.com/IBySStW.png

**Comment by zachgarcia1** [comment]
any update on when this will be fixed?

**Comment by abhibeckert** [comment]
@zachgarcia1 the next release will fix it. We'll have a release candidate in the coming weeks. How soon after that the stable build is will depend if bugs are found

**Comment by ryanolton** [comment]
I just noticed on macOS 10.12.3 that I no longer see an issue with the icon. Are others still seeing an issue after updating to 10.12.3?

![screen shot 2017-02-15 at 23 42 32](https://cloud.githubusercontent.com/assets/1325073/23007728/7cc7daae-f3d8-11e6-8b3a-25b77e5c630d.png)

**Comment by poliquin** [comment]
@ryanolton Yes, I see the issue on 10.12.3

<img width="309" alt="dock_icons" src="https://cloud.githubusercontent.com/assets/360123/23008152/cb4c2a38-f3db-11e6-80e0-dd64b8ea636c.png">

It is especially visible when using another app with a dark background. In my case, iTerm2 is running full screen behind the dock.

**Comment by abhibeckert** [comment]
There are 10 separate images in the icon, at different sizes and for retina and non-retina screens, as well as rules defining which image will be drawn.

Only some of the images have this problem. For some people, the problem sizes will never be drawn.

**Comment by ryanolton** [comment]
@poliquin @abhibeckert you guys are right; I do still see an issue, but only when I'm using a retina screen. Thanks for shedding light on all the number of images used for that icon.

**Comment by mkwsra** [comment]
I really would like to close this issue, since it seems to be solved, perhaps couple of you guys can confirm?

I tested it with Dark UI and bright one too!

_MacOS Sierra ver: 10.12.4
SequelPro 1.1.2
Build 4541 (602e11a)_

<img width="461" alt="screen shot 2017-02-19 at 1 28 33 pm" src="https://cloud.githubusercontent.com/assets/1743919/23101577/665c62a2-f69f-11e6-94dd-8f9f6efd68a6.png">

**Comment by jamesstidard** [comment]
@mkwsra I still have it on mine. I'm using a macbook pro retina 13" if that helps.
 
Sierra 10.12.3 (16D32)
Sequel Pro 1.1.2 Build 4541 (602e11a)

<img width="72" alt="screen shot 2017-02-19 at 11 00 25 am" src="https://cloud.githubusercontent.com/assets/1797906/23101738/a26d3684-f692-11e6-961d-6dc76d80dcc0.png">

**Comment by abhibeckert** [comment]
@mkwsra it's not solved. Just inconsistent.

For example it happens on the internal display on my MacBook Pro, but not my external 4K display (even though it's also retina).

**Comment by abhibeckert** [comment]
I've made a new icon that should fix this issue. I'd appreciate if some people test it out and report any issues.

You'll need to copy it into the bundle Resources directory, then restart your mac (to clear the system icon cache).

[appIcon.icns.zip](https://github.com/sequelpro/sequelpro/files/788987/appIcon.icns.zip)

**Comment by scherii** [comment]
@abhibeckert Thank you, just replaced mine. I'm on 10.12.3, it's fine now.

**Comment by jacobwallace** [comment]
Thanks for the new icon, @abhibeckert. I had to remove from the dock and re-add to clear the cache. Looks great now!

**Comment by gintechsystems** [comment]
I just tried downloading the icon resource from @abhibeckert. I replaced it, removed the app from the dock and restarted my iMac. Didn't resolve the issue. I am also on 10.12.3.

**Comment by abhibeckert** [comment]
@gintechsystems it's almost certainly a cache issue, some caches do persist across restart.

Try the this:

```
touch /Applications/Sequel\ Pro.app/
touch /Applications/Sequel\ Pro.app/Contents/Info.plist 
killall Dock
```

**Comment by gintechsystems** [comment]
@abhibeckert, that worked. Nice catch, thank you!

**Comment by beornlake** [comment]
@abhibeckert Thanks, that fixed up the issue perfectly.

**Comment by Envo** [comment]
It seems like fixed in the latest version of macOS (10.12.4)

**Comment by samholmes** [comment]
It's still an issue on 1.1.2 for me.

I'm running macOS 10.12.4 / 15" MBP with Touch Bar. I had to use the PNG supplemented here: http://i.imgur.com/IBySStW.png

**Comment by LukeStanbery89** [comment]
Still happening for me, but only on my Macbook's built in display. The issue does not occur on external displays.

<img width="153" alt="screen shot 2017-07-20 at 1 23 27 pm" src="https://user-images.githubusercontent.com/9427182/28432941-8628d6e8-6d4f-11e7-89ad-cba3cde2ddc3.png">

<img width="466" alt="screen shot 2017-07-20 at 1 30 53 pm" src="https://user-images.githubusercontent.com/9427182/28432984-b892d76e-6d4f-11e7-8ed1-b21a095745f6.png">

**Comment by jonasiliaens** [comment]
Still an issue, for me, changed the icon + reboot + 
touch /Applications/Sequel\ Pro.app/
touch /Applications/Sequel\ Pro.app/Contents/Info.plist 
killall Dock
+ reboot, didn't help

<img width="225" alt="schermafbeelding 2017-08-22 om 22 34 58" src="https://user-images.githubusercontent.com/9570991/29586178-2a3fd584-878a-11e7-84df-063731e51f08.png">

<img width="584" alt="schermafbeelding 2017-08-22 om 22 34 19" src="https://user-images.githubusercontent.com/9570991/29586156-190876ea-878a-11e7-8a00-6af3b4f07a90.png">

**Comment by bartclaeys** [comment]
Long shot, but is this logo available in SVG? I understand it's quite impossible with the complex shadows and reflections, but maybe there is a stylized version available in SVG format?
