### ISSUE TITLE
User Manager exception with MariaDB 10.3.4 for table column Delete_history_priv

### ISSUE THREAD

**Issue by perarg** [sequelpro/sequelpro#2982]
This is an error i get when i try to see the users.

```
NSUnknownKeyException

[<NSManagedObject 0x608000a880c0> setValue:forUndefinedKey:]: the entity Privileges is not key value coding-compliant for the key "Truncate_versioning_priv".

(
	0   CoreFoundation                      0x00007fff7b2c92cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff900e048d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff7b2c9219 -[NSException raise] + 9
	3   Sequel Pro                          0x00000001000ba81d -[SPUserManager _initializeSchemaPrivsForChild:fromData:] + 941
	4   Sequel Pro                          0x00000001000b9dfb -[SPUserManager _initializeTree:] + 1213
	5   Sequel Pro                          0x00000001000b962e -[SPUserManager _initializeUsers] + 208
	6   Sequel Pro                          0x00000001000b94af -[SPUserManager windowDidLoad] + 312
	7   AppKit                              0x00007fff78da6c78 -[NSWindowController _windowDidLoad] + 682
	8   AppKit                              0x00007fff78d46ce3 -[NSWindowController window] + 110
	9   Sequel Pro                          0x00000001000bab0d -[SPUserManager beginSheetModalForWindow:completionHandler:] + 68
	10  Sequel Pro                          0x0000000100036d45 -[SPDatabaseDocument showUserManager:] + 306
	11  AppKit                              0x00007fff79053c8a -[NSToolbarButton sendAction:to:] + 75
	12  AppKit                              0x00007fff78f90750 -[NSToolbarItemViewer mouseDown:] + 5193
	13  AppKit                              0x00007fff7963024f -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 6341
	14  AppKit                              0x00007fff7962ca6c -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 1942
	15  AppKit                              0x00007fff7962bf0a -[NSWindow(NSEventRouting) sendEvent:] + 541
	16  Sequel Pro                          0x000000010012e644 -[SPWindow sendEvent:] + 783
	17  AppKit                              0x00007fff794b0681 -[NSApplication(NSEvent) sendEvent:] + 1145
	18  AppKit                              0x00007fff78d2b427 -[NSApplication run] + 1002
	19  AppKit                              0x00007fff78cf5e0e NSApplicationMain + 1237
	20  Sequel Pro                          0x0000000100002454 start + 52
	21  ???                                 0x0000000000000001 0x0 + 1
)
```

**Comment by dmoagx** [comment]
"{{Truncate_versioning_priv}}" (related command "{{DELETE HISTORY}}") was added in MariaDB 10.3.4
Before that it was called "{{Delete_versioning_rows_priv}}" (related command "{{DELETE VERSIONING ROWS}}"), but doesn't seem to have been in a release.

**Comment by jaisgit** [comment]
FYI - I see a similar error also with mariadb 10.3.7

`NSUnknownKeyException

[<NSManagedObject 0x10b5d1730> setValue:forUndefinedKey:]: the entity Privileges is not key value coding-compliant for the key "Delete_history_priv".

(
	0   CoreFoundation                      0x00007fff89c6f452 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff8444cf7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff89c6f399 -[NSException raise] + 9
	3   Sequel Pro                          0x00000001000ba81d -[SPUserManager _initializeSchemaPrivsForChild:fromData:] + 941
	4   Sequel Pro                          0x00000001000b9dfb -[SPUserManager _initializeTree:] + 1213
	5   Sequel Pro                          0x00000001000b962e -[SPUserManager _initializeUsers] + 208
	6   Sequel Pro                          0x00000001000b94af -[SPUserManager windowDidLoad] + 312
	7   AppKit                              0x00007fff8a249927 -[NSWindowController _windowDidLoad] + 592
	8   AppKit                              0x00007fff8a1e643e -[NSWindowController window] + 110
	9   Sequel Pro                          0x00000001000bab0d -[SPUserManager beginSheetModalForWindow:completionHandler:] + 68
	10  Sequel Pro                          0x0000000100036d45 -[SPDatabaseDocument showUserManager:] + 306
	11  Sequel Pro                          0x00000001000f3681 -[SPWindowController performSelector:withObject:] + 172
	12  libsystem_trace.dylib               0x00007fff8352407a _os_activity_initiate + 75
	13  AppKit                              0x00007fff8a43edbd -[NSApplication sendAction:to:from:] + 460
	14  AppKit                              0x00007fff8a43eb57 -[NSMenuItem _corePerformAction] + 336
	15  AppKit                              0x00007fff8a43e8b7 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
	16  libsystem_trace.dylib               0x00007fff8352407a _os_activity_initiate + 75
	17  AppKit                              0x00007fff8a4d0e54 -[NSMenu performActionForItemAtIndex:] + 131
	18  AppKit                              0x00007fff8a4d0dc7 -[NSMenu _internalPerformActionForItemAtIndex:] + 35
	19  AppKit                              0x00007fff8a4d0c1f -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 107
	20  AppKit                              0x00007fff8a375fd9 NSSLMMenuEventHandler + 708
	21  HIToolbox                           0x00007fff8c0387be _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1231
	22  HIToolbox                           0x00007fff8c037c48 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 404
	23  HIToolbox                           0x00007fff8c04d9e6 SendEventToEventTarget + 40
	24  HIToolbox                           0x00007fff8c09799a _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 411
	25  HIToolbox                           0x00007fff8c0c2d5b SendMenuCommandWithContextAndModifiers + 59
	26  HIToolbox                           0x00007fff8c0c2d0c SendMenuItemSelectedEvent + 188
	27  HIToolbox                           0x00007fff8c0c2be8 _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
	28  HIToolbox                           0x00007fff8c0c3596 _ZL14MenuSelectCoreP8MenuData5PointdjPP13OpaqueMenuRefPt + 711
	29  HIToolbox                           0x00007fff8c0c3230 _HandleMenuSelection2 + 460
	30  AppKit                              0x00007fff8a3610fa _NSHandleCarbonMenuEvent + 277
	31  AppKit                              0x00007fff8a1d613d _DPSNextEvent + 1906
	32  AppKit                              0x00007fff8a1d5226 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	33  AppKit                              0x00007fff8a1c9d80 -[NSApplication run] + 682
	34  AppKit                              0x00007fff8a193368 NSApplicationMain + 1176
	35  Sequel Pro                          0x0000000100002454 start + 52
)`

**Comment by Muffinman** [comment]
Sorry hadn't spotted this issue was open when searching, I've published a fix in #3167.

**Comment by FRANZEE** [comment]
Sorry for necroposting i have the same issue, how i can apply this fix? Cloning this repository and build on my mac? Because release-1.1.2 still have this bug... 
Thx

**Comment by Muffinman** [comment]
Yes, there's not been a new release for a while so building from source is the only way I'm afraid.

**Comment by rowanbeentje** [comment]
https://sequelpro.com/test-builds will allow you to verify the fix which will be included in the next release version.
