### ISSUE TITLE
Crashing after close connection tab

### ISSUE THREAD

**Issue by microdesign** [sequelpro/sequelpro#3611]
I wait around six months for update to solve this bug 

Every time I close a connection tab the app crash 

macOS Mojave 10.14.5 (18F132)

bot all update for the system and for sequelpro are applied

**Comment by iammichiel** [comment]
Same here.

**Comment by charlielee** [comment]
Use the latest test build where this issue is resolved. :) See pinned #3116 

https://sequelpro.com/test-builds

**Comment by microdesign** [comment]
I will wait for the official one, I thank there is bugfix coming

**Comment by iammichiel** [comment]
@charlielee The test build does not resolve the issue. The app still crashes whenever a tab is closed.

**Comment by brunosserrao** [comment]
> Use the latest test build where this issue is resolved. :) See pinned #3116
> 
> https://sequelpro.com/test-builds

Works fine the new version Sequel-Pro-Build-97c1b85783

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705
