### ISSUE TITLE
MySQL 8 issues

### ISSUE THREAD

**Issue by RobertHana** [sequelpro/sequelpro#3632]
the app crashes fetching table list from MySQL8 server

**Comment by dennisprudlo** [comment]
Duplicate of #2699 

This has already been reported.

The bug is fixed but we have to wait for the new version to release. Until then you can download one of the latest test builds where you can connect to MySQL 8 servers (https://sequelpro.com/test-builds).

**Comment by roma4u** [comment]
@dennisprudlo What kind of build to download so that there is no error with MySQL 8 ?

**Comment by dennisprudlo** [comment]
just download the latest build. The issue was fixed 3 years ago all succeeding build should connect to MySQL 8 servers.

**Comment by GpingFeng** [comment]
my sequelpro is the latest version. But it does still not work.

**Comment by GpingFeng** [comment]
![image](https://user-images.githubusercontent.com/20135760/80948559-f181bd80-8e24-11ea-8be0-b10d22be61b6.png)

**Comment by Hubertnator** [comment]
@GpingFeng Use the latest [nightly build](https://sequelpro.com/test-builds)
Or switch to TablePlus, DBeaver or MySQL Workbench seen as this software has pretty much no support (last commit 7 months ago).
